name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "100fdeb1-45d6-4fa9-8cc3-8f1c80dda204"
          heroku_app_name: "tododemo-app1"
          heroku_email: "mnihon3@gmail.com"
          justlogin: true
      - run: heroku auth:whoami
